cc_library(
    name = "models",
    srcs = [
        "ListNode.cpp",
        "TreeNode.cpp",
    ],
    hdrs = ["ListNode.h", "TreeNode.h"],
    deps = [
        "@nlohmann_json//:json",
    ],
    visibility = ["//visibility:public"],
)
