cc_library(
    name = "models",
    srcs = [
        "ListNode.cpp",
        "TreeNode.cpp",
        "TreeNodeNext.cpp",
    ],
    hdrs = [
        "ListNode.h",
        "TreeNode.h",
        "TreeNodeNext.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@nlohmann_json//:json",
    ],
)
