cc_binary(
    name = "1114",
    srcs = ["//multi_threading/1114:main.cpp"],
    deps = [],
)

cc_binary(
    name = "1115",
    srcs = ["//multi_threading/1115:main.cpp"],
    deps = [],
)

cc_binary(
    name = "1116",
    srcs = ["//multi_threading/1116:main.cpp"],
    deps = [],
)

cc_binary(
    name = "1117",
    srcs = ["//multi_threading/1117:main.cpp"],
    deps = [],
)

cc_binary(
    name = "1195",
    srcs = ["//multi_threading/1195:main.cpp"],
    deps = [],
)
