load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_test(
    name = "solution",
    srcs = ["src/main.rs"],
    deps = [
        "@rust_problems//:solution_lib",
    ],
    edition = "2021"
)
